create table exercises
(
    created_at   timestamp(6) not null,
    id           bigint generated by default as identity,
    updated_at   timestamp(6) not null,
    description  varchar(255) not null,
    image_uri    varchar(255) not null,
    muscle_group varchar(255) not null check ((muscle_group in
                                               ('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'ABS', 'FOREARMS'))),
    name         varchar(255) not null,
    primary key (id)
);
create table routine_exercises
(
    order_position integer      not null,
    created_at     timestamp(6) not null,
    exercise_id    bigint       not null,
    id             bigint generated by default as identity,
    routine_id     bigint       not null,
    updated_at     timestamp(6) not null,
    primary key (id)
);
create table routine_sets
(
    set_number              integer      not null,
    target_repetitions      integer      not null default 0,
    target_weight           float(53)    not null default 0.0,
    id                      bigint generated by default as identity,
    routine_and_exercise_id bigint       not null,
    target_rest_seconds     bigint       not null default 120,
    notes                   varchar(255),
    target_weight_unit      varchar(255) not null check ((target_weight_unit in ('KG', 'LBS'))),
    primary key (id)
);
create table routines
(
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity,
    updated_at  timestamp(6) not null,
    user_id     bigint       not null,
    description varchar(255) ,
    name        varchar(255) not null,
    primary key (id)
);
create table session_exercises
(
    order_position integer      not null,
    created_at     timestamp(6) not null,
    exercise_id    bigint       not null,
    id             bigint generated by default as identity,
    session_id     bigint       not null,
    updated_at     timestamp(6) not null,
    primary key (id)
);
create table session_sets
(
    completed               boolean      not null default false,
    effective_repetitions   integer      not null default 0,
    effective_weight        float(53)    not null default 0.0,
    set_number              integer      not null,
    created_at              timestamp(6) not null,
    effective_rest_time     bigint       not null default 120,
    id                      bigint generated by default as identity,
    session_and_exercise_id bigint       not null,
    updated_at              timestamp(6) not null,
    effective_weight_unit   varchar(255) not null check ((effective_weight_unit in ('KG', 'LBS'))),
    notes                   varchar(255),
    primary key (id)
);
create table sessions
(
    completed        boolean      not null default false,
    created_at       timestamp(6) not null,
    date             timestamp(6) not null,
    duration_seconds bigint       not null,
    id               bigint generated by default as identity,
    routine_id       bigint,
    updated_at       timestamp(6) not null,
    user_id          bigint       not null,
    notes            varchar(255),
    primary key (id)
);
create table users
(
    created_at    timestamp(6) not null,
    id            bigint generated by default as identity,
    updated_at    timestamp(6) not null,
    email         varchar(255) not null unique,
    name          varchar(255) not null,
    password_hash varchar(255) not null,
    username      varchar(255) not null unique,
    primary key (id)
);


alter table if exists routine_exercises
    add constraint FK_routine_exercises_exercise_id foreign key (exercise_id) references exercises;


alter table if exists routine_exercises
    add constraint FK_routine_exercises_routine_id foreign key (routine_id) references routines on delete cascade;


alter table if exists routine_sets
    add constraint FK_routine_sets_routine_and_exercises_id foreign key (routine_and_exercise_id) references routine_exercises on delete cascade;

alter table if exists routines
    add constraint FK_routines_user_id foreign key (user_id) references users on delete cascade;

alter table if exists session_exercises
    add constraint FK_session_exercises_exercise_id foreign key (exercise_id) references exercises;

alter table if exists session_exercises
    add constraint FK_session_exercises_session_id foreign key (session_id) references sessions on delete cascade;

alter table if exists session_sets
    add constraint FK_session_sets_session_and_exercise_id foreign key (session_and_exercise_id) references session_exercises on delete cascade;

alter table if exists sessions
    add constraint FK_sessions_routine_id foreign key (routine_id) references routines on delete set null;

alter table if exists sessions
    add constraint FK_sessions_user_id foreign key (user_id) references users on delete cascade;
