create table refresh_tokens
(
    id         bigint generated by default as identity,
    family_id  uuid         not null,
    token_hash varchar(255) not null unique,
    user_id    bigint       not null,
    created_at timestamp(6) not null,
    revoked_at timestamp(6),
    expires_at timestamp(6) not null,
    primary key (id)
);

alter table if exists refresh_tokens
    add constraint FK_user_id foreign key (user_id) references users on delete cascade;